# Local Variables
# ===============
#
# Pass custom values to the `make` cli as:
# > make start pg_name=foobar
#

include ../../Makefile
# curr_project?=projects/pushid
# base_dir?=../..

# filename=script

# clean: filename=clean
# populate: filename=populate
# read-data: filename=read-data
# operator: filename=operator
# overloaded-functions: filename=overloaded-functions
# clean populate read-data operator overloaded-functions: exec-file

