# Local Variables
# ===============
#
# Pass custom values to the `make` cli as:
# > make start pg_name=foobar
#

include ../../Makefile
# curr_project?=projects/pushid
# base_dir?=../..

clean: filename=clean
clean: exec-file

populate-clean: filename=populate-clean
populate-dirty: filename=populate-dirty
columns-size: filename=columns-size
populate-clean populate-dirty columns-size: seed exec-file


