# Local Variables
# ===============
#
# Pass custom values to the `make` cli as:
# > make start pg_name=foobar
#

include ../../Makefile
# curr_project?=projects/pushid
# base_dir?=../..

clean: filename=clean
clean: exec-file


populate: filename=populate_and_calculate
testcount: filename=test-count
populate testcount: seed exec-file


