# Local Variables
# ===============
#
# Pass custom values to the `make` cli as:
# > make start pg_name=foobar
#

include ../../Makefile
# curr_project?=projects/pushid
# base_dir?=../..

filename=script


simple: filename=simple
custom-fields: filename=custom-fields
pick-random-array: filename=pick-random-array
generate-random-numbers: filename=generate-random-numbers
generate-random-birthdays: filename=generate-random-birthdays
generate-seed: filename=generate-seed

simple custom-fields pick-random-array generate-random-numbers generate-random-birthdays generate-seed: exec-file

