# Local Variables
# ===============
#
# Pass custom values to the `make` cli as:
# > make start pg_name=foobar
#

include ../../Makefile
# curr_project?=projects/pushid
# base_dir?=../..

# clean: filename=clean

# %: 
#	@$(MAKE) exec-file filename=$@

#clean ranking less_4_rank_comments cte likes: exec-file
# .PHONY: Makefile ../../Makefile


