# Local Variables
# ===============
#
# Pass custom values to the `make` cli as:
# > make start pg_name=foobar
#

include ../../Makefile
# curr_project?=projects/pushid
# base_dir?=../..

filename=script

clean: filename=clean
populate: filename=populate
read-data: filename=read-data
operator: filename=operator
poly-functions: filename=poly-functions
clean populate read-data operator poly-functions: exec-file

