# Local Variables
# ===============
#
# Pass custom values to the `make` cli as:
# > make start pg_name=foobar
#

include ../../Makefile
# curr_project?=projects/pushid
# base_dir?=../..

# filename=script

# populate: filename=populate
# read-data: filename=read-data
# populate read-data: exec-file

